export { PartnerHero } from "./PartnerHero";
export { WhyOMS } from "./WhyOMS";
export { BigSlicesFeature } from "./BigSlicesFeature";
export { PartnerOptions } from "./PartnerOptions";
export { LocationFit } from "./LocationFit";
export { ProductFeatures } from "./ProductFeatures";
export { PartnerType } from "./PartnerType";
export { OpportunityCTA } from "./OpportunityCTA";
export { PartnerForm } from "./PartnerForm";
